Fix #158 : Search box for oData entitities to add
OData/ODataConnectedService pull request #161
Opened 2020-07-23 21:26 UTC by unchase

Fix #158 :

![search_text_box](https://user-images.githubusercontent.com/29679226/88340226-2165a080-cd44-11ea-9b3d-e442214c0d8f.gif)

Added the tests below:

To **SchemaTypesViewModelTests:**

- [x] `FillingSearchText_ShouldFilterSchemaTypes`.

To **OperationImportsViewModelTests:**

- [x] `FillingSearchText_ShouldFilterOperationImports`.

2020-07-23 21:29 UTC, unchase commented
@habbes @marabooy @KenitoInc @ElizabethOkerio @gathogojr @paulodero ready for review

2020-07-31 21:29 UTC, UM001 commented
nice!

2020-08-31 05:22 UTC, paulodero requested changes
Public properties/methods need to be documented. You can as well include bound operations as part of search results if necessary.

2020-08-31 05:22 UTC, paulodero commented on src/ViewModels/SchemaTypesViewModel.cs
> +        {
Could you document the public properties.

2020-08-31 05:22 UTC, paulodero commented on src/ViewModels/OperationImportsViewModel.cs
> +        public IEnumerable<OperationImportModel> FilteredOperationImports
Document the public properties.

2020-08-31 05:22 UTC, paulodero commented on src/ViewModels/OperationImportsViewModel.cs
> +                    : OperationImports.Where(x => x.Name.StartsWith(SearchText, StringComparison.InvariantCultureIgnoreCase));
Do you think it is necessary to do a fuzzy match here instead?

2020-08-31 08:14 UTC, unchase commented on src/ViewModels/OperationImportsViewModel.cs
> +                    : OperationImports.Where(x => x.Name.StartsWith(SearchText, StringComparison.InvariantCultureIgnoreCase));
> Do you think it is necessary to do a fuzzy match here instead?

I think it is not necessary. But I can replace `StartsWith` with `Contains`.

2020-08-31 10:36 UTC, paulodero commented on src/ViewModels/OperationImportsViewModel.cs
> +        public string SearchText
would be great if you can document this as well.

2020-08-31 10:38 UTC, paulodero approved these changes
You can document the undocumented public properties/methods then :shipit:

2020-08-31 11:39 UTC, unchase commented
> You can document the undocumented public properties/methods then :shipit:

Done!

2020-09-08 08:19 UTC, habbes approved these changes
Looks good to me.

2020-10-02 18:39 UTC, unchase commented
Can you tell me when you plan to merge the PR?

2020-10-07 12:07 UTC, habbes commented
Hi @unchase, apologies for the delay. We have experienced some delays in transferring the extension to .Net Foundation on VS Marketplace. As soon as this process is finalized, we will publish a new release.

2020-10-21 12:07 UTC, merged