Fix #48 Metadata URL with values in Query String
OData/ODataConnectedService pull request #177
Opened 2020-11-13 20:13 UTC by facundo91

Fix #48 Metadata URL with values in Query String

* Fix applied
* Test added
* Some typos fixed

2020-11-13 20:13 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/OData/ODataConnectedService?pullRequest=177) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/OData/ODataConnectedService?pullRequest=177) before we can accept your contribution.<br/><br/>:x: facundo91 [sign now](https://cla.dotnetfoundation.org/OData/ODataConnectedService?pullRequest=177)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/OData/ODataConnectedService?pullRequest=177) it.</sub>

2020-11-30 08:47 UTC, marabooy commented
@facundo91 can you rebase this kindly.

2020-11-30 08:56 UTC, marabooy approved these changes

2020-11-30 09:01 UTC, gathogojr commented on src/ViewModels/ConfigODataEndpointViewModel.cs
>                      this.Endpoint = this.Endpoint.TrimEnd('/') + "/$metadata";
@facundo91 @marabooy Do we need to make any change to this line or are we happy losing the query string part?

2020-11-30 09:08 UTC, marabooy commented on src/ViewModels/ConfigODataEndpointViewModel.cs
>                      this.Endpoint = this.Endpoint.TrimEnd('/') + "/$metadata";
I think this should change as the current logic won't work for valid uri's and may generate some invalid cases.
@facundo91 can you fix this in this Pr so that the query string is preserved even when we modify the URI.

2020-12-01 07:46 UTC, marabooy requested changes

2020-12-01 07:46 UTC, marabooy commented on src/ViewModels/ConfigODataEndpointViewModel.cs
>                      this.Endpoint = this.Endpoint.TrimEnd('/') + "/$metadata";
@facundo91 Kindly address the above comment.

2020-12-01 12:50 UTC, facundo91 commented
I will address this PR today or the day after. Thank you

2020-12-01 13:21 UTC, facundo91 commented on src/ViewModels/ConfigODataEndpointViewModel.cs
>                      this.Endpoint = this.Endpoint.TrimEnd('/') + "/$metadata";
This is the requested in the Issue #48, am I loosing something?
This should work with urls as:  `http://[host]:[port]/odata/$metadata?api-version=1.0`
It passes all existing tests, I could add a new test case or test scenario if missing.

2020-12-01 13:33 UTC, marabooy commented on src/ViewModels/ConfigODataEndpointViewModel.cs
>                      this.Endpoint = this.Endpoint.TrimEnd('/') + "/$metadata";
So the issue in this case is that a url that has the following data will probably not work 
`http://host/odata/?api-version=2` the above will remove the query string.

2020-12-01 13:34 UTC, marabooy commented on src/ViewModels/ConfigODataEndpointViewModel.cs
>                      this.Endpoint = this.Endpoint.TrimEnd('/') + "/$metadata";
You could in this case just save the query string and then append it at the end or use a url builder to break it up and add it back.

2021-02-22 17:41 UTC, KenitoInc commented
Hey @facundo91 
Kindly
- Address review comments
- Rebase the branch and resolve conflicts.

2022-09-27 07:50 UTC, closed without merging

2022-09-27 07:50 UTC, Nthemba commented
Issue fixed by PR #311