Fix #176 : Create new Service Proxy or regenerate existing Service Proxy fails (OData V3, WCF Data Services)
OData/ODataConnectedService pull request #178
Opened 2020-11-20 18:30 UTC by unchase

Fix #176.
There are a few errors in v0.11.1:

![issue176](https://user-images.githubusercontent.com/29679226/99836282-e733d080-2b76-11eb-8c42-16f80bfdff84.gif)

![issue176_1](https://user-images.githubusercontent.com/29679226/99836287-ea2ec100-2b76-11eb-94d0-d1f5c265cf60.gif)

![issue176_2](https://user-images.githubusercontent.com/29679226/99836291-ebf88480-2b76-11eb-8e32-f2527615d921.gif)

With metadata:

```xml
<?xml version="1.0" standalone="yes" ?>
<edmx:Edmx Version="1.0" xmlns:edmx="http://schemas.microsoft.com/ado/2006/04/edmx">
  <edmx:DataServices xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" m:DataServiceVersion="2.0">
    <Schema Namespace="Simple" xmlns="http://schemas.microsoft.com/ado/2006/04/edmx">
      <EntityType Name="TestType">
        <Key>
          <PropertyRef Name="KeyProp" />
        </Key>
        <Property Name="KeyProp" Type="Edm.Int32" Nullable="false" />
        <Property Name="ValueProp" Type="Edm.String" Nullable="false" />
      </EntityType>
    </Schema>
  </edmx:DataServices>
</edmx:Edmx> 
```

Fixed.

---

Added the tests below:

To **EdmHelperTests:**

- [x] `TestGetSchemaTypesWithNullModel`;
- [x] `TestGetOperationImportsWithNullModel`;
- [x] `TestGetBoundOperationsWithNullModel`.

To **:**

- [x] `TestV2AddGeneratedClientCode_GeneratesCodeForv2_ForVB`;
- [x] `TestV2AddGeneratedClientCode_GeneratesCodeForv2`.

2020-11-20 19:01 UTC, unchase commented
@habbes @marabooy @KenitoInc @ElizabethOkerio @gathogojr @paulodero ready for review

There is a false positive error:
![image](https://user-images.githubusercontent.com/29679226/99839420-bb671980-2b7b-11eb-90d8-b1b624661ff8.png)

How can I fix it?

2020-11-24 13:10 UTC, marabooy approved these changes

2020-11-25 19:04 UTC, KenitoInc requested changes
We can fix the ".......must be called on the UI thread" errors in V3 the way I did in V4.
Compare the `V3CodeGenDescriptor.cs` and `V4CodeGenDescriptor.cs`

2020-11-26 05:09 UTC, KenitoInc commented on src/CodeGeneration/V4CodeGenDescriptor.cs
> +            var referenceFolder = this.GetReferenceFileFolder();
Why are you adding `this.` ?

2020-11-26 08:42 UTC, unchase commented on src/CodeGeneration/V4CodeGenDescriptor.cs
> +            var referenceFolder = this.GetReferenceFileFolder();
![image](https://user-images.githubusercontent.com/29679226/100327493-69d7e800-2fdc-11eb-940a-ae361eec3a55.png)

2020-11-26 09:25 UTC, KenitoInc approved these changes
LGTM

2020-11-30 08:43 UTC, gathogojr approved these changes
LGTM

2020-11-30 08:46 UTC, merged