Set the most logical config defaults for the wizard
OData/ODataConnectedService pull request #187
Opened 2020-12-22 14:11 UTC by gathogojr

This pull request fixes #181 

Set the most logical config defaults for the wizard

2020-12-22 14:12 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/OData/ODataConnectedService?pullRequest=187) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/OData/ODataConnectedService?pullRequest=187) before we can accept your contribution.<br/><br/>:x: gathogojr [sign now](https://cla.dotnetfoundation.org/OData/ODataConnectedService?pullRequest=187)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/OData/ODataConnectedService?pullRequest=187) it.</sub>

2021-01-13 14:42 UTC, habbes commented on src/Common/UserSettingsPersistenceHelper.cs
> +            return providerId + "." + name + ".xml";
What was the purpose of changing from `_` to `.`  in the filename?

2021-01-13 14:49 UTC, habbes commented on src/Models/UserSettings.cs
> +            userSettings.MruEndpoints = new ReadOnlyObservableCollection<string>(userSettings.mruEndpoints);
How come here you are not checking whether `userSettings != null` but in other cases you in this file you are?

2021-01-13 14:52 UTC, habbes commented on src/Models/UserSettings.cs
> +                logger: logger);
If I understand correctly, this automatically attempts to load the settings from file when you instantiate `new UserSettings()` even without calling `userSettings.Load()`?

2021-01-13 15:03 UTC, habbes approved these changes
Thanks for cleaning things up.

2021-01-14 08:16 UTC, KenitoInc requested changes
A few comments and questions!

2021-01-14 08:16 UTC, KenitoInc commented on src/Models/UserSettings.cs
> +        [IgnoreDataMember]
Also add `[IgnoreDataMember]` to `CustomHttpHeaders` since we my have authentication tokens

2021-01-14 08:16 UTC, KenitoInc commented on src/Models/UserSettings.cs
> +            IgnoreUnexpectedElementsAndAttributes = true;
Maybe you add a comment similar to the way you did for `UseDataServiceCollection` and `EnableNamingAlias`

2021-01-14 08:16 UTC, KenitoInc commented on src/Models/UserSettings.cs
>          public ObservableCollection<string> MruEndpoints { get; set; }
Since we have a public `get` and `set` here, I think `MruEndPoints` can be manipulated wrongly here.

2021-01-14 08:16 UTC, KenitoInc commented on src/ODataConnectedServiceWizard.cs
> +                ConfigODataEndpointViewModel.EdmxVersion = ServiceConfig?.EdmxVersion;
Why did we stop adding the `Endpoint` and `ServiceName` to the View model?

2021-01-14 12:44 UTC, marabooy commented on src/Common/UserSettingsPersistenceHelper.cs
> +                            using (var writer = XmlWriter.Create(stream, new XmlWriterSettings { Indent = true }))
Do we need to indent this or can this remain the same as the file is not usually read by human?

2021-01-14 12:46 UTC, marabooy commented on src/Models/UserSettings.cs
> +        public UserSettings(string configName = "Settings")
Docs for the ctor.

2021-01-14 12:57 UTC, marabooy commented on src/ODataConnectedServiceWizard.cs
> +            Pages.Add(ConfigODataEndpointViewModel);
To this. or not to?

2021-01-15 07:50 UTC, gathogojr commented on src/Common/ExtensionMethods.cs
> +        public static void CopyPropertiesFrom(this object target, object source)
Done

2021-01-15 07:52 UTC, gathogojr commented on src/Common/UserSettingsPersistenceHelper.cs
> +                            using (var writer = XmlWriter.Create(stream, new XmlWriterSettings { Indent = true }))
During development when you may need to verify the content, it's extremely hard to follow. I reasoned there would be no harm in having it properly formatted

2021-01-15 08:02 UTC, gathogojr commented on src/Common/UserSettingsPersistenceHelper.cs
> +            return providerId + "." + name + ".xml";
The new config file gives the users a new clean slate with default settings as they originally used to be. The old config file would for example have `EnableNamingAlias`, `UseDataServiceCollection` and `IgnoreUnexpectedElementsAndAttributes` default values all set with a value of `false` due to previous mishandling of the default values.

2021-01-15 08:02 UTC, gathogojr commented on src/Models/UserSettings.cs
> +        public UserSettings(string configName = "Settings")
Done

2021-01-15 08:06 UTC, gathogojr commented on src/ODataConnectedServiceWizard.cs
> +                ConfigODataEndpointViewModel.EdmxVersion = ServiceConfig?.EdmxVersion;
The approach I adopting is to have the control binding to a single `UserSettings` instance newed up at [this point](https://github.com/OData/ODataConnectedService/pull/187/files#diff-00999e34e0165406b5257c8c0a958b3a089653a8b8c0cb618d1be46af253f0d3R52). `Endpoint` and `ServiceName` are properties of `UserSettings` and the controls bind to them. That's the reason I'm not adding them to the view model.

2021-01-15 08:08 UTC, gathogojr commented on src/ODataConnectedServiceWizard.cs
> +            Pages.Add(ConfigODataEndpointViewModel);
Whatever code analyzer we're using (or VS default analyzer) considers `this.` superfluous so I dropped it in quite a number of places where possible

2021-01-15 08:23 UTC, gathogojr commented on src/Models/UserSettings.cs
> +            userSettings.MruEndpoints = new ReadOnlyObservableCollection<string>(userSettings.mruEndpoints);
Fixed indirectly after refactoring the logic

2021-01-15 08:29 UTC, gathogojr commented on src/Models/UserSettings.cs
> +                logger: logger);
Yes. We're primarily interested in the MRU endpoints since we always use them to populate the Endpoint dropdown. That way we have everything that we need for purposes of rendering the view. Note that we don't use any other setting from the config file.

2021-01-15 08:29 UTC, gathogojr commented on src/Models/UserSettings.cs
> +        [IgnoreDataMember]
Done

2021-01-15 08:29 UTC, gathogojr commented on src/Models/UserSettings.cs
> +            IgnoreUnexpectedElementsAndAttributes = true;
Done

2021-01-15 08:34 UTC, gathogojr commented on src/Models/UserSettings.cs
>          public ObservableCollection<string> MruEndpoints { get; set; }
That is a concern I also had and set out to address but in the end I had to trade off since using a `ReadOnlyObservableCollection` inhibited two-way binding with the view causing the wizard not to work as expected

2021-01-18 07:57 UTC, KenitoInc reviewed
Minor comments

2021-01-18 07:57 UTC, KenitoInc commented on src/Models/UserSettings.cs
> +                    if (this.MruEndpoints[i].Equals(mruEndpoint, StringComparison.Ordinal))
We need to be consistent on the use or otherwise of `this.`

2021-01-18 07:57 UTC, KenitoInc commented on src/Properties/AssemblyInfo.cs
> +[assembly: AssemblyVersion("0.11.2.0")]
Was the version bump deliberate?
Keep an eye on it during release

2021-01-18 08:27 UTC, gathogojr commented on src/Properties/AssemblyInfo.cs
> +[assembly: AssemblyVersion("0.11.2.0")]
@KenitoInc We'll most definitely need to bump up the version but I'll verify the appropriate version number to use

2021-01-18 08:31 UTC, gathogojr commented on src/Models/UserSettings.cs
> +                    if (this.MruEndpoints[i].Equals(mruEndpoint, StringComparison.Ordinal))
Noted and fixed

2021-01-18 09:14 UTC, KenitoInc approved these changes
LGTM

2021-01-19 08:08 UTC, merged