Allow users to store custom Http headers and proxy credentials
OData/ODataConnectedService pull request #216
Opened 2021-03-10 17:12 UTC by dr-consit

Allow users to store custom Http headers and proxy credentials in `ConnectedService.json`.

Adds a checkbox to "Include Custom Http Headers" and "Include Proxy Network Credentials" allowing the user to store these in `ConnectedService.json` if so desired.

2021-03-10 17:16 UTC, dr-consit commented
Implements #215

2021-03-11 06:42 UTC, marabooy requested changes

2021-03-11 06:42 UTC, marabooy commented on src/Common/ExtensionsHelper.cs
> +        public ServiceConfigurationV4 ExtendedData { get; set; }
```suggestion
        public UserSettings ExtendedData { get; set; }
```

2021-03-11 06:42 UTC, marabooy commented on src/Models/UserSettings.cs
> +        private List<string> excludedSchemaTypes;
```suggestion
        private List<string> excludedSchemaTypes;
```

2021-03-11 08:38 UTC, dr-consit commented on src/Common/ExtensionsHelper.cs
> +        public ServiceConfigurationV4 ExtendedData { get; set; }
Applied and rebased

2021-03-11 08:38 UTC, dr-consit commented on src/Models/UserSettings.cs
> +        private List<string> excludedSchemaTypes;
Applied and rebased

2021-03-11 08:40 UTC, marabooy approved these changes
Looks good just one small change to whitepsce in the test cases

2021-03-11 08:40 UTC, marabooy commented on test/ODataConnectedService.Tests/ODataConnectedServiceWizardTests.cs
> +                endpointPage.UserSettings.IncludeWebProxy = true;
```suggestion
                endpointPage.UserSettings.IncludeWebProxy = true; 
```
nit: Whitespace

2021-03-11 08:49 UTC, dr-consit commented on test/ODataConnectedService.Tests/ODataConnectedServiceWizardTests.cs
> +                endpointPage.UserSettings.IncludeWebProxy = true;
Applied and rebased.

2021-03-12 13:30 UTC, KenitoInc requested changes

2021-03-12 13:30 UTC, KenitoInc commented on src/Views/ConfigODataEndpoint.xaml
> +                Content="Save http headers in ConnectedService.json"
```suggestion
                Content="Save custom http headers in ConnectedService.json"
```

2021-03-12 13:30 UTC, KenitoInc commented on src/Views/ConfigODataEndpoint.xaml
> +                    Content="Save credentials in ConnectedService.json"
```suggestion
                    Content="Save web proxy credentials in ConnectedService.json"
```

2021-03-12 13:30 UTC, KenitoInc commented on test/ODataConnectedService.Tests/ODataConnectedServiceHandlerTest.cs
> +            //CustomHttpHeaders should be null when StoreCustomHttpHeaders is false since we are not saving them to DesignerData
```suggestion
            // CustomHttpHeaders should be null when StoreCustomHttpHeaders is false since we are not saving them to DesignerData
```

2021-03-15 08:11 UTC, dr-consit commented on src/Views/ConfigODataEndpoint.xaml
> +                Content="Save http headers in ConnectedService.json"
Applied and rebased

2021-03-15 08:11 UTC, dr-consit commented on src/Views/ConfigODataEndpoint.xaml
> +                    Content="Save credentials in ConnectedService.json"
Applied and rebased

2021-03-15 08:11 UTC, dr-consit commented on test/ODataConnectedService.Tests/ODataConnectedServiceHandlerTest.cs
> +            //CustomHttpHeaders should be null when StoreCustomHttpHeaders is false since we are not saving them to DesignerData
Applied and rebased

2021-03-15 08:46 UTC, marabooy commented
@dr-consit  what about this set of items which are igored by [this](https://github.com/OData/ODataConnectedService/blob/042f7a390b8d2fa6c5055dfedc59e2bcbf319afe/src/Models/UserSettings.cs#L278).

2021-03-15 09:07 UTC, dr-consit commented
> 
> 
> @dr-consit what about this set of items which are igored by [this](https://github.com/OData/ODataConnectedService/blob/042f7a390b8d2fa6c5055dfedc59e2bcbf319afe/src/Models/UserSettings.cs#L278). should we address this as it is related

I think it makes sense to not store headers and credentials in the isolated storage (roaming profile). For this reason I left the Ignore attributes in place, so they don't get written to this XML file.

This was part of the reason why I thought it made sense to change `ExtendedData` in `ConnectedServiceJsonFileData` to `ServiceConfigurationV4`.

I interpreted `UserSettings` as being responsible for this XML file, while I read ServiceConfiguration(V4) as being the definition for the json files. The json file is written using ServiceConfiguration(V4) (through SetExtendedDesignerData) but read using UserSettings, because of the, to my eyes, curious definition in `ConnectedServiceJsonFileData`. The only references I could find were in `OpenConnectedServiceJsonFileButton_Click`.

2021-04-15 09:07 UTC, KenitoInc approved these changes
LGTM

2021-04-20 07:49 UTC, merged