Add Obsolete Attributes
OData/ODataConnectedService pull request #217
Opened 2021-03-29 21:29 UTC by KenitoInc

Add support for Obsolete Attributes in the generate code.

Here is how the annotation looks in XML. It can be applied to a type, entity set, singleton, property, navigation property, function or action. If a type is marked as deprecated, it is not necessary to mark members of that type as deprecated, nor is it necessary to annotate any usage of that type in entity sets, singletons, properties, navigation properties, functions, or actions.

```xml
  <EntityType Name="outlookTask" BaseType="Microsoft.OutlookServices.outlookItem" ags:IsMaster="true" ags:WorkloadName="Task" ags:EnabledForPassthrough="true">
    <Annotation Term="Org.OData.Core.V1.Revisions">
      <Collection>
        <Record>
          <PropertyValue Property = "Date" Date="2020-08-20"/>
          <PropertyValue Property = "Version" String="2020-08/Tasks_And_Plans"/>
          <PropertyValue Property = "Kind" EnumMember="Org.OData.Core.V1.RevisionKind/Deprecated"/>
          <PropertyValue Property = "Description" String="The Outlook tasks API is deprecated and will stop returning data on August 20, 2022. Please use the new To Do API."/>
          <PropertyValue Property = "RemovalDate" Date="2022-08-20"/>
        </Record>
      </Collection>
    </Annotation>
    ...
  </EntityType>
```xml

2021-04-13 15:19 UTC, habbes requested changes

2021-04-13 15:19 UTC, habbes commented on src/Templates/ODataT4CodeGenerator.cs
> +        if (collection != null && collection.Count() > 0)
```suggestion
        if (collection?.Any())
```

2021-04-13 15:19 UTC, habbes commented on src/Templates/ODataT4CodeGenerator.cs
> +        IEnumerable<IEdmExpression> collection = model.VocabularyAnnotations(this.context.EdmModel).Where(x => x.Term.Name == "Revisions")
Why aren't you also checking the namespace of the annotation term?

2021-04-13 15:19 UTC, habbes commented on src/Templates/ODataT4CodeGenerator.cs
> +            IEdmRecordExpression element = semanticElement.Elements.FirstOrDefault() as IEdmRecordExpression;
```suggestion
            IEdmRecordExpression element = semanticElement?.Elements.FirstOrDefault() as IEdmRecordExpression;
```

Since you're using `FirstOrDefault()`, I think you should check for nulls, just in case.

2021-04-13 15:19 UTC, habbes commented on src/Templates/ODataT4CodeGenerator.cs
> +            IEdmStringConstantExpression description = element.Properties.Where(x => x.Name == "Description").Select(x => x.Value).FirstOrDefault() as IEdmStringConstantExpression;
```suggestion
            IEdmStringConstantExpression description = element?.Properties.Where(x => x.Name == "Description").Select(x => x.Value).FirstOrDefault() as IEdmStringConstantExpression;
```

2021-04-13 15:19 UTC, habbes commented on src/Templates/ODataT4CodeGenerator.cs
> +    private IEdmStringConstantExpression GetRevisionsAnnotation(IEdmVocabularyAnnotatable model)
Maybe rename `model` parameter to something else, like `schemaElement` to avoid confusion with Edm model.

2021-04-13 15:19 UTC, habbes commented on src/Templates/ODataT4CodeGenerator.cs
> +    private IEdmStringConstantExpression GetRevisionsAnnotation(IEdmVocabularyAnnotatable model)
Out of curiosity, why are we returning the `StringConsantExpression` instead of just returning the description as a `string`?

2021-04-13 15:19 UTC, habbes commented on src/Templates/ODataT4CodeGenerator.cs
> +    internal abstract void WriteContextEntitySetProperty(string entitySetName, string entitySetFixedName, string originalEntitySetName, string entitySetElementTypeName, string description, string rev
I think we have too many parameters on some of these Write methods. I don't think it's sustainable or maintainable to keep adding more.. I suggest we use a dictionary are an object to hold all the additional metadata like descriptions, deprecation messages, etc.:

```c#
class CodeElementMetadata {
   public string Description { get; set; }
   public string DeprecationMessage { get; set; }
}
```
Not sure about the name of the class, or whether we should have a common class for all types of code elements (entity sets, methods, etc.) or different classes.

2021-04-14 03:41 UTC, ElizabethOkerio commented on src/Templates/ODataT4CodeGenerator.cs
> +        IEnumerable<IEdmExpression> collection = model.VocabularyAnnotations(this.context.EdmModel).Where(x => x.Term.Name == "Revisions")
Add a check for the Revision Kind as well because we can have other Revision Kinds (Added, Modified) in the model

2021-04-15 07:57 UTC, marabooy commented on src/Templates/ODataT4CodeGenerator.cs
> +this.Write("\")]\r\n\r\n");
```suggestion
this.Write("\")]\r\n\");
```

2021-04-15 07:57 UTC, marabooy commented on src/Templates/ODataT4CodeGenerator.cs
> +this.Write("    [global::System.ObsoleteAttribute(\"");
We could probably just write this using one invocation to this.Write and string.Concat

2021-04-15 07:57 UTC, marabooy commented on src/Templates/ODataT4CodeGenerator.cs
> +this.Write("        [global::System.ObsoleteAttribute(\"");
Same for string.Concat to reduce LOC

2021-04-22 08:06 UTC, KenitoInc commented on src/Templates/ODataT4CodeGenerator.cs
> +        if (collection != null && collection.Count() > 0)
I have fix by using `collection != null && collection.Any()`

2021-04-22 08:06 UTC, KenitoInc commented on src/Templates/ODataT4CodeGenerator.cs
> +        IEnumerable<IEdmExpression> collection = model.VocabularyAnnotations(this.context.EdmModel).Where(x => x.Term.Name == "Revisions")
#Resolved

2021-04-22 08:06 UTC, KenitoInc commented on src/Templates/ODataT4CodeGenerator.cs
> +            IEdmStringConstantExpression description = element.Properties.Where(x => x.Name == "Description").Select(x => x.Value).FirstOrDefault() as IEdmStringConstantExpression;
#Resolved

2021-04-22 08:07 UTC, KenitoInc commented on src/Templates/ODataT4CodeGenerator.cs
> +    private IEdmStringConstantExpression GetRevisionsAnnotation(IEdmVocabularyAnnotatable model)
#Resolved

2021-04-22 08:07 UTC, KenitoInc commented on src/Templates/ODataT4CodeGenerator.cs
> +    internal abstract void WriteContextEntitySetProperty(string entitySetName, string entitySetFixedName, string originalEntitySetName, string entitySetElementTypeName, string description, string rev
I changed to use a `Dictionary` that stores all revision annotations.

2021-04-22 08:07 UTC, KenitoInc commented on src/Templates/ODataT4CodeGenerator.cs
> +        IEnumerable<IEdmExpression> collection = model.VocabularyAnnotations(this.context.EdmModel).Where(x => x.Term.Name == "Revisions")
#Resolved

2021-04-22 08:08 UTC, KenitoInc commented on src/Templates/ODataT4CodeGenerator.cs
> +this.Write("\")]\r\n\r\n");
I don't have control on how the generated code is written.

2021-04-22 08:08 UTC, KenitoInc commented on src/Templates/ODataT4CodeGenerator.cs
> +this.Write("    [global::System.ObsoleteAttribute(\"");
I don't have control on how the generated code is written.

2021-04-22 08:08 UTC, KenitoInc commented on src/Templates/ODataT4CodeGenerator.cs
> +this.Write("        [global::System.ObsoleteAttribute(\"");
I don't have control on how the generated code is written.

2021-04-23 12:54 UTC, habbes commented on src/Templates/ODataT4CodeGenerator.ttinclude
> +
Could you explain what this is for?

2021-04-23 12:56 UTC, habbes commented on src/Templates/ODataT4CodeGenerator.cs
> +            // Add empty dictionary to the anonymous type
Which anonymous type are you referring to here?

2021-04-23 12:57 UTC, habbes commented on src/Templates/ODataT4CodeGenerator.cs
> +                RevisionDescription = emptyDict
Why not create the empty dict here: `RevisionDescription = new Dictionary<string, string>()`?

2021-04-23 13:00 UTC, habbes commented on src/Templates/ODataT4CodeGenerator.cs
> +                propertyInfo.RevisionDescription);
Logically, I think it would make more sense to group the property metadata-related parameters together, then the `useDataServiceCollection` last. But I still think adding more params is unsustainable.

2021-04-23 13:58 UTC, habbes commented on src/Templates/ODataT4CodeGenerator.cs
> +        if (collection != null && collection.Any())
```suggestion
        if (collection?.Any())
```

2021-04-23 13:59 UTC, habbes commented on src/Templates/ODataT4CodeGenerator.cs
> +            IEdmCollectionExpression semanticElement = collection.FirstOrDefault() as IEdmCollectionExpression;
Maybe you can verify that `semanticElement` is not null since you're using `FirstOrDefault()`?

2021-04-26 07:00 UTC, habbes commented on src/Templates/ODataT4CodeGenerator.cs
> +        if (!revisionAnnotations.TryGetValue("Deprecated", out string revisionDescription))
Maybe "Deprecated" should be a constant?

2021-04-26 07:09 UTC, habbes commented on src/Templates/ODataT4CodeGenerator.cs
> +                revisionsAnnotation.Add(name, description);
Is there a guarantee the `FirstOrDefault()` cannot return `null`? What if the revision kind is missing from the xml document?

2021-04-26 08:13 UTC, odero commented on src/Templates/ODataT4CodeGenerator.cs
> +                revisionsAnnotation.Add(name, description);
Hence the second part of my comment. Kind is a required field. Meaning if it returns `null` it should be an error which should be handled/propagated appropriately and/or reported

2021-04-29 06:54 UTC, KenitoInc commented on src/Templates/ODataT4CodeGenerator.ttinclude
> +
Since we are not adding `ObsoleteAttribute` to dynamic types, we are assigning an empty dictionary to the property in the anonymous type.
Note: An anonymous type cannot have a null property.

2021-04-29 06:58 UTC, KenitoInc commented on src/Templates/ODataT4CodeGenerator.cs
> +            // Add empty dictionary to the anonymous type
`propertyInfo`
Check the entire `internal void WritePropertiesForStructuredType(IEdmStructuredType structuredType)` method.

2021-04-29 06:59 UTC, KenitoInc commented on src/Templates/ODataT4CodeGenerator.cs
> +                RevisionDescription = emptyDict
You can't do that in anonymous types.

2021-04-29 07:00 UTC, KenitoInc commented on src/Templates/ODataT4CodeGenerator.cs
> +                propertyInfo.RevisionDescription);
I have updated the property name,
All `RevisionAnnotations` are in one dictionary.

2021-04-29 07:07 UTC, KenitoInc commented on src/Templates/ODataT4CodeGenerator.cs
> +        if (collection != null && collection.Any())
`collection?.Any()` returns a `bool?`. Unless I add an explicit cast as below to get a `bool`
`(bool)(collection?.Any())`

2021-04-29 07:12 UTC, odero commented on src/Templates/ODataT4CodeGenerator.cs
> +        if (collection != null && collection.Any())
if (collection?.Any() == true)

2021-04-29 07:18 UTC, KenitoInc commented on src/Templates/ODataT4CodeGenerator.cs
> +        if (!revisionAnnotations.TryGetValue("Deprecated", out string revisionDescription))
#Resolved

2021-04-29 08:35 UTC, KenitoInc commented on src/Templates/ODataT4CodeGenerator.cs
> +                revisionsAnnotation.Add(name, description);
I don't there is a config for failing silently.
If required fields are missing, we should throw an exception.
I have updated the code appropriately and added tests.

2021-04-29 08:35 UTC, KenitoInc commented on test/ODataConnectedService.Tests/CodeGenReferences/EntityAndNavPropertiesMarkedObsolete.xml
> +﻿<?xml version="1.0" encoding="utf-8" ?>
Done

2021-05-11 09:17 UTC, habbes approved these changes

2021-05-17 06:01 UTC, gathogojr commented on src/Templates/ODataT4CodeGenerator.cs
> +            this.WriteContextEntitySetProperty(camelCaseEntitySetName, GetFixedName(camelCaseEntitySetName), entitySet.Name, GetFixedName(entitySetElementTypeName), GetDescriptionAnnotation(entitySet
@KenitoInc The naming is a bit confusing. You changed the method signature to accept an additional parameter `revisionAnnotations` then adopted `GetRevisionsAnnotation` as the name for method that returns that.

2021-05-17 06:06 UTC, gathogojr commented on src/Templates/ODataT4CodeGenerator.cs
> +                    RevisionAnnotations = GetRevisionsAnnotation(property)
Related to my other comment https://github.com/OData/ODataConnectedService/pull/217/files#r633241743
LHS you have annotations while RHS you have annotation
```csharp
RevisionAnnotations = GetRevisionsAnnotation(property)
```

2021-05-17 06:24 UTC, gathogojr commented on src/Templates/ODataT4CodeGenerator.cs
> +            IEdmCollectionExpression semanticElement = collection.FirstOrDefault() as IEdmCollectionExpression;
```suggestion
        IEdmCollectionExpression semanticElement = collection?.FirstOrDefault() as IEdmCollectionExpression;
```
Since `.Any()` is always executed whenever the collection is not null, I think you can forgo that and just call `.FirstOrDefault()`

2021-05-17 06:45 UTC, gathogojr commented on test/ODataConnectedService.Tests/Templates/ODataT4CodeGeneratorTests.cs
> +            // results.Errors.Should().BeEmpty();
Since you changed the `TreatWarningsAsErrors` setting to `false`, should you still leave this line commented?

2021-05-18 08:36 UTC, KenitoInc commented on test/ODataConnectedService.Tests/Templates/ODataT4CodeGeneratorTests.cs
> +        public void RevisionsAnnotationMissingRevisionKindThrows()
It's not a breaking since this will be only thrown when you have an incorrect AnnotationXml.
`Kind` and `Description` are required properties.

2021-05-18 08:36 UTC, KenitoInc commented on src/Templates/ODataT4CodeGenerator.cs
> +            IEdmCollectionExpression semanticElement = collection.FirstOrDefault() as IEdmCollectionExpression;
#Resolved

2021-05-18 08:37 UTC, KenitoInc commented on src/Templates/ODataT4CodeGenerator.cs
> +                    RevisionAnnotations = GetRevisionsAnnotation(property)
#Resolved

2021-05-18 08:37 UTC, KenitoInc commented on src/Templates/ODataT4CodeGenerator.cs
> +            this.WriteContextEntitySetProperty(camelCaseEntitySetName, GetFixedName(camelCaseEntitySetName), entitySet.Name, GetFixedName(entitySetElementTypeName), GetDescriptionAnnotation(entitySet
#Resolved

2021-05-18 08:38 UTC, KenitoInc commented on test/ODataConnectedService.Tests/Templates/ODataT4CodeGeneratorTests.cs
> +            // results.Errors.Should().BeEmpty();
I have uncommented the line.
However still some warnings are showing up as errors. I have opted to set the warning level as 0 (to ignore all warnings) and check for compilation errors only.

2021-05-18 09:31 UTC, gathogojr approved these changes
:shipit:

2021-05-18 09:38 UTC, merged