support vs2022
OData/ODataConnectedService pull request #295
Opened 2022-06-02 09:21 UTC by ElizabethOkerio

2022-06-07 07:23 UTC, gathogojr commented on src/ODataConnectedService_vs2022/Properties/AssemblyInfo.cs
> +// [assembly: AssemblyVersion("1.0.*")]
```suggestion
```

2022-06-07 07:24 UTC, gathogojr commented on src/ODataConnectedService/source.extension.vsixmanifest
> +        <Icon>Resources\Icon.png</Icon>
Why?

2022-06-07 09:28 UTC, habbes commented
Some initial thoughts:

We seem to have 3 sln files and some of them seem redundant.

The `ODataConnectedService.Tests.sln` contains all the projects. This makes the other sln files feel redundant. Maybe we can keep this one solution and remove the rest. And also rename it from `ODataConnectedService.Tests.sln` to something else. Since now it contains more than just the `ODataConnectedService` project (i.e. it also contains the CLI and the CodeGen lib), maybe it can be renamed to something like `ODataTools.sln`.

If the aim was to separate the CLI project from the connected service, we could have 2 solution files `OData.Cli.sln` and `ODataConnectedService.sln`. However, I'm not sure if this is more beneficial than just having a single solution, especially since they would all reference the CodeGen common project.

The new project for VS 2022 is called `ODataConnectedService_vs2022`. Since this is probably what's going to the "current" version, I suggest we rename it to `ODataConnectedService` and then rename the project targeting VS 2019 and lower to something like `ODataConnectedService_Legacy`.

2022-06-07 12:16 UTC, KenitoInc commented on src/Microsoft.OData.CodeGen/Microsoft.OData.CodeGen.csproj
> +    <PackageReference Include="Microsoft.Bcl.AsyncInterfaces">
What's the criteria behind choosing which packages to move to `PackageReference`?

2022-06-07 12:16 UTC, KenitoInc commented on src/ODataConnectedService/source.extension.vsixmanifest
> +        <Icon>Resources\Icon.png</Icon>
The 2 images look the same, with same size

2022-06-07 13:01 UTC, habbes commented
Are there any steps I need to take to get this to run locally? I have tried to debug the `ODataConnectedService_vs2022` project after opening the solution in VS 2022, and it fails. I also tried `dotnet restore` and it also fails.

![VsBuildError](https://user-images.githubusercontent.com/8460169/172385560-af616261-1713-48c9-a7d8-dec7aca42e75.png)


![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/8460169/172385804-15e30c06-ffa1-4974-90ab-a1dceac7687d.png)

![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/8460169/172386072-9bf9b2b5-379c-4ec5-9ad5-b89deb15456f.png)

2022-06-07 19:23 UTC, ElizabethOkerio commented on src/Microsoft.OData.CodeGen/Microsoft.OData.CodeGen.csproj
> +    <PackageReference Include="Microsoft.Bcl.AsyncInterfaces">
all packages from nuget are referenced using the `PackageReference`

2022-06-09 07:04 UTC, ElizabethOkerio commented
> Are there any steps I need to take to get this to run locally? I have tried to debug the `ODataConnectedService_vs2022` project after opening the solution in VS 2022, and it fails. I also tried `dotnet restore` and it also fails.
> 
> ![VsBuildError](https://user-images.githubusercontent.com/8460169/172385560-af616261-1713-48c9-a7d8-dec7aca42e75.png)
> 
> ![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/8460169/172385804-15e30c06-ffa1-4974-90ab-a1dceac7687d.png)
> 
> ![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/8460169/172386072-9bf9b2b5-379c-4ec5-9ad5-b89deb15456f.png)

Have pulled this branch again and was able to run it. Can you try the other VSIX for visual studio 2019 and lower versions and let me know if it works.

2022-06-17 09:17 UTC, ElizabethOkerio commented
> Some initial thoughts:
> 
> We seem to have 3 sln files and some of them seem redundant.
> 
> The `ODataConnectedService.Tests.sln` contains all the projects. This makes the other sln files feel redundant. Maybe we can keep this one solution and remove the rest. And also rename it from `ODataConnectedService.Tests.sln` to something else. Since now it contains more than just the `ODataConnectedService` project (i.e. it also contains the CLI and the CodeGen lib), maybe it can be renamed to something like `ODataTools.sln`.
> 
> If the aim was to separate the CLI project from the connected service, we could have 2 solution files `OData.Cli.sln` and `ODataConnectedService.sln`. However, I'm not sure if this is more beneficial than just having a single solution, especially since they would all reference the CodeGen common project.
> 
> The new project for VS 2022 is called `ODataConnectedService_vs2022`. Since this is probably what's going to the "current" version, I suggest we rename it to `ODataConnectedService` and then rename the project targeting VS 2019 and lower to something like `ODataConnectedService.Legacy`.

From the discussions that we had, Legacy  is not the right word to use. We settled for `ODataConnectedService_Latest` for `VS 2022` project

2022-06-17 09:20 UTC, ElizabethOkerio commented
> > Some initial thoughts:
> > We seem to have 3 sln files and some of them seem redundant.
> > The `ODataConnectedService.Tests.sln` contains all the projects. This makes the other sln files feel redundant. Maybe we can keep this one solution and remove the rest. And also rename it from `ODataConnectedService.Tests.sln` to something else. Since now it contains more than just the `ODataConnectedService` project (i.e. it also contains the CLI and the CodeGen lib), maybe it can be renamed to something like `ODataTools.sln`.
> > If the aim was to separate the CLI project from the connected service, we could have 2 solution files `OData.Cli.sln` and `ODataConnectedService.sln`. However, I'm not sure if this is more beneficial than just having a single solution, especially since they would all reference the CodeGen common project.
> > The new project for VS 2022 is called `ODataConnectedService_vs2022`. Since this is probably what's going to the "current" version, I suggest we rename it to `ODataConnectedService` and then rename the project targeting VS 2019 and lower to something like `ODataConnectedService.Legacy`.
> > The project that targets earlier versions will maintain it's name `ODataConnectedService` and the project that targets `VS 2022` will be called `ODataConnectedService_Latest`

The project that targets earlier versions will maintain it's name `ODataConnectedService` and the project that targets `VS 2022` will be called `ODataConnectedService_Latest`

2022-07-12 11:48 UTC, gathogojr commented on azure-pipelines.yml
> +  sln: '$(connectedServiceDir)\ODataCodeGenTools.sln'
Was this change necessary?

2022-07-12 11:49 UTC, gathogojr commented on azure-pipelines.yml
> -  testSln: '$(connectedServiceDir)\ODataConnectedService.Tests.sln'
Why did we remove the test solution?

2022-07-12 11:49 UTC, gathogojr commented on azure-pipelines.yml
> -    - task: NuGetCommand@2
Why did we remove the tests solution?

2022-07-12 12:12 UTC, gathogojr commented on src/ODataConnectedService_VS2022Plus/source.extension.vsixmanifest
> +        <DisplayName>OData Connected Service 2022plus</DisplayName>
Please seek opinion from other contributors regarding what best to use as display name and in labels

2022-07-12 16:40 UTC, ElizabethOkerio commented on azure-pipelines.yml
> -    - task: NuGetCommand@2
we didn't remove the test solution. The test sln had all the other projects. So we just named that soluton to ODataCodeGenTools.sln. which has the test project and all the other projects.

2022-07-12 18:36 UTC, ElizabethOkerio commented on azure-pipelines.yml
> +  productBinPath1: '$(connectedServiceDir)\src\ODataConnectedService_VS2022Plus\bin\$(BuildConfiguration)'
resolved

2022-07-12 18:42 UTC, ElizabethOkerio commented on src/ODataConnectedService_VS2022Plus/source.extension.vsixmanifest
> +        <DisplayName>OData Connected Service 2022plus</DisplayName>
fixed

2022-07-12 19:01 UTC, ElizabethOkerio commented on src/SharedFiles/License.txt
> +
it is different from which content? It is the same. It is the same file shared between the two projects.

2022-07-12 19:32 UTC, ElizabethOkerio commented on src/ODataConnectedService/ODataConnectedService.csproj
> +    <Service Include="{508349B6-6B84-4DF5-91F0-309BEEBAD82D}" />
This was there before. Haven't added it.

2022-07-13 08:09 UTC, gathogojr commented on src/SharedFiles/License.txt
> +
Compare below with this:
![image](https://user-images.githubusercontent.com/28291332/178683795-2298a6ed-d2c6-4c4c-8f87-95652b9de42e.png)
First line on the screenshot has **MIT License (MIT)**...

2022-07-13 08:20 UTC, ElizabethOkerio commented on src/SharedFiles/License.txt
> +
seen. updated

2022-07-13 08:26 UTC, gathogojr approved these changes

2022-07-13 08:36 UTC, habbes requested changes
Seems there are some things which have not been updated.

- The main `README.md` still assumes the old directory and project structure. It also assumes VS 2017 and 2019
- I tried running the `build.cmd` locally and it fails with an error message saying it couldn't copy `src/ODataConnectedService`. When I tried the command on an older branch, it succeeds. Probably needs to be updated. The `build.cmd` also references `ODataConnectedService.msbuild`, I don't know if that file also contains references that need to be updated. Frankly, I don't know if we use either of these files. Should we consider removing them?

2022-07-13 13:54 UTC, merged